# Generated by Django 3.0 on 2020-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bssservices', '0002_auto_20200117_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservicecharge',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Night'), (3, 'Travel')], default=1),
        ),
    ]
