# Generated by Django 3.0 on 2020-01-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bssservices', '0003_additionalservicecharge_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalServiceCharge',
            new_name='SpeficServiceCharge',
        ),
    ]
